services:
  scraper:
    # Dockerfile is in this directory
    build: .

    # The working directory INSIDE the container
    working_dir: /app

    # Fix file permissions
    user: '${UID}:${GID}'

    # Required for Chromium sandbox without granting SYS_ADMIN privileges
    security_opt:
      - seccomp:unconfined
    shm_size: 1gb

    # Volumes:
    volumes:
      # Mount local code to /app
      - .:/app

    # The command to be executed
    command: sh -c "npm install && npm start"
